title: The Official Hindi Site of Buddha and his Dhamma
description: Buddha and his Dhamma's Official Hindi Website. We are making Hindi Buddhist Literature available on the Internet. A movement of enlightenment.
permalink: /:basename/